### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by YannickStoffers** [YannickStoffers/IntroCee2018#1]
- [x] Icoontjes fixen op homepage
- [x] Banner
- [x] Beschrijving thema
- [x] Datum check
- [ ] Organisatie verhaaltje
- [ ] Organisatie foto's
- [ ] Grab list Sleeping en Clothing omdraaien
- [ ] Grab list Rubber ducky toevoegen
- [x] Sign-ups backend
- [x] Sign-ups overview op website voor commissieleden
- [x] Sign-ups autofill wanneer iemand ingelogd is op svcover.nl
- [x] Sign-ups voor de barbecue toevoegen
- [x] Stylesheets aanpassen
